# Generated by Django 6.0.2 on 2026-02-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_drawdown_percent', models.DecimalField(decimal_places=2, default=5.0, help_text='Porcentaje máximo de drawdown permitido antes de cortar operativa', max_digits=5)),
                ('default_lot_size', models.DecimalField(decimal_places=2, default=0.01, help_text='Lote por defecto para nuevas operaciones', max_digits=6)),
                ('equity_profit_target', models.DecimalField(decimal_places=2, default=0.0, help_text='Cierre masivo al alcanzar esta equidad (0 = Desactivado)', max_digits=10)),
                ('global_stop_loss_points', models.IntegerField(default=100, help_text='Stop loss global expresado en puntos/pips')),
                ('is_trading_active', models.BooleanField(default=True, help_text='Botón de pánico: desactiva la apertura de nuevas operaciones')),
            ],
            options={
                'verbose_name_plural': 'Risk Settings',
            },
        ),
    ]
