# Generated by Django 6.0.2 on 2026-02-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('account_id', models.BigIntegerField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'Equity Snapshots',
                'ordering': ['-timestamp'],
            },
        ),
    ]
