# Generated by Django 6.0.2 on 2026-02-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0002_equitysnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='risksettings',
            name='is_profit_monitor_active',
            field=models.BooleanField(default=False, help_text='Estado del monitor de profit'),
        ),
        migrations.AddField(
            model_name='risksettings',
            name='profit_target_percent',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Meta de profit en % para cierre masivo', max_digits=5),
        ),
    ]
