# Generated by Django 6.0.2 on 2026-02-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0003_risksettings_is_profit_monitor_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolProfitTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True)),
                ('target_profit_usd', models.DecimalField(decimal_places=2, default=0.0, help_text='Meta de profit en USD para este símbolo', max_digits=10)),
                ('is_active', models.BooleanField(default=False, help_text='Estado del monitor para este símbolo')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
