# Generated by Django 6.0.2 on 2026-02-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0004_symbolprofittarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='risksettings',
            name='manual_initial_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Capital inicial manual para referencia de rendimiento (ej: 560 USD)', max_digits=12),
        ),
    ]
