# Generated by Django 6.0.2 on 2026-02-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0005_risksettings_manual_initial_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolprofittarget',
            name='is_active',
        ),
        migrations.AddField(
            model_name='symbolprofittarget',
            name='is_loss_active',
            field=models.BooleanField(default=False, help_text='Estado del monitor de pérdida para este símbolo'),
        ),
        migrations.AddField(
            model_name='symbolprofittarget',
            name='is_profit_active',
            field=models.BooleanField(default=False, help_text='Estado del monitor de profit para este símbolo'),
        ),
        migrations.AddField(
            model_name='symbolprofittarget',
            name='target_loss_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Límite de pérdida en USD para este símbolo (ej: 50.00)', max_digits=10),
        ),
    ]
