# Generated by Django 6.0.2 on 2026-02-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0006_remove_symbolprofittarget_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketWatchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbols', models.TextField(default='EURUSD,GBPUSD,USDJPY,GOLD', help_text='Símbolos a monitorear separados por coma')),
                ('timeframe_htf', models.CharField(default='H1', help_text='Timeframe para Estructura (H1, H4, D1)', max_length=10)),
                ('timeframe_ltf', models.CharField(default='M5', help_text='Timeframe para Confirmación (M1, M5, M15)', max_length=10)),
                ('is_scanner_active', models.BooleanField(default=True, help_text='Activa/Desactiva el escaneo de Price Action')),
                ('poi_margin_pips', models.DecimalField(decimal_places=2, default=2.0, help_text='Margen de error en pips para zona POI', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Market Watch Settings',
            },
        ),
        migrations.CreateModel(
            name='MarketWatchSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('SCANNING', 'Scanning'), ('IN_POI', 'In POI'), ('ENTRY_READY', 'Entry Ready')], default='SCANNING', max_length=20)),
                ('setup_type', models.CharField(blank=True, max_length=10, null=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
