# Generated by Django 6.0.2 on 2026-02-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0007_marketwatchsettings_marketwatchsignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketWatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('setup_type', models.CharField(max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=15)),
                ('take_profit', models.DecimalField(decimal_places=5, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Market Watch History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='marketwatchsettings',
            name='symbols',
            field=models.TextField(default='ALL', help_text="Símbolos a monitorear. Usa 'ALL' para escanear todo el Market Watch de MT5."),
        ),
        migrations.AlterField(
            model_name='marketwatchsettings',
            name='timeframe_htf',
            field=models.CharField(default='H1', help_text='Timeframe para Estructura (H1, H4, M30, D1)', max_length=10),
        ),
        migrations.AlterField(
            model_name='marketwatchsettings',
            name='timeframe_ltf',
            field=models.CharField(default='M5', help_text='Timeframe para Confirmación (M1, M5, M15, M30)', max_length=10),
        ),
    ]
