# Generated by Django 6.0.2 on 2026-02-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0008_marketwatchhistory_alter_marketwatchsettings_symbols_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsettings',
            name='is_price_action_active',
            field=models.BooleanField(default=True, help_text='Activa/Desactiva la estrategia de Price Action (Estructura/POI)'),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='is_smi_active',
            field=models.BooleanField(default=True, help_text='Activa/Desactiva la estrategia de SMI (Momentum)'),
        ),
    ]
