# Generated by Django 6.0.2 on 2026-02-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0009_marketwatchsettings_is_price_action_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsettings',
            name='smi_sl_pips',
            field=models.IntegerField(default=20, help_text='Stop Loss en pips para señales SMI'),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='smi_tp_pips',
            field=models.IntegerField(default=60, help_text='Take Profit en pips para señales SMI'),
        ),
        migrations.AddField(
            model_name='risksettings',
            name='default_broker_symbol',
            field=models.CharField(default='EURUSD', help_text='Símbolo de referencia para sincronizar hora del broker cuando no hay posiciones', max_length=50),
        ),
        migrations.AddField(
            model_name='risksettings',
            name='magic_number',
            field=models.IntegerField(default=123456, help_text='Número mágico para identificar órdenes de este panel en MT5'),
        ),
        migrations.AddField(
            model_name='risksettings',
            name='max_deviation',
            field=models.IntegerField(default=20, help_text='Slippage/Desviación máxima en puntos al ejecutar órdenes'),
        ),
    ]
