# Generated by Django 6.0.2 on 2026-02-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0010_marketwatchsettings_smi_sl_pips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsettings',
            name='is_stochastic_active',
            field=models.BooleanField(default=True, help_text='Activa/Desactiva el Estocástico como confluencia con SMI'),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='scan_timeframes',
            field=models.TextField(default='M5,M15,M30,H1', help_text='Temporalidades a evaluar, separadas por coma'),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='stoch_d_period',
            field=models.IntegerField(default=3, help_text='Periodo %D del Estocástico'),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='stoch_k_period',
            field=models.IntegerField(default=14, help_text='Periodo %K del Estocástico'),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='stoch_overbought',
            field=models.IntegerField(default=80, help_text='Nivel de sobrecompra del Estocástico'),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='stoch_oversold',
            field=models.IntegerField(default=20, help_text='Nivel de sobreventa del Estocástico'),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='stoch_slowing',
            field=models.IntegerField(default=3, help_text='Suavizado (Slowing) del Estocástico'),
        ),
        migrations.AddField(
            model_name='marketwatchsignal',
            name='strategy_name',
            field=models.CharField(blank=True, help_text='Estrategia que generó la señal (ej: SMI+STOCH, PRICE_ACTION)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='marketwatchsignal',
            name='timeframe',
            field=models.CharField(blank=True, help_text='Temporalidad donde se detectó la señal', max_length=10, null=True),
        ),
    ]
