# Generated by Django 6.0.2 on 2026-02-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0011_marketwatchsettings_is_stochastic_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsignal',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketwatchsignal',
            name='is_dismissed',
            field=models.BooleanField(default=False, help_text="Si el usuario ha 'eliminado' la tarjeta manualmente"),
        ),
    ]
