# Generated by Django 6.0.2 on 2026-02-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0012_marketwatchsignal_dismissed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsettings',
            name='is_supply_demand_active',
            field=models.BooleanField(default=True, help_text='Activa/Desactiva la estrategia S&D (Oferta y Demanda)'),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='sd_imbalance_threshold',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplicador del tamaño promedio de vela para considerar el FVG/Impulso como válido', max_digits=5),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='sd_timeframe_htf',
            field=models.CharField(default='H4', help_text='Timeframe HTF para buscar Velas Base e Imbalances (FVG)', max_length=10),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='sd_timeframe_ltf',
            field=models.CharField(default='M15', help_text='Timeframe LTF para Confirmación (CHoCH)', max_length=10),
        ),
    ]
