# Generated by Django 6.0.2 on 2026-02-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0013_marketwatchsettings_is_supply_demand_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketWatchHistory',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='is_price_action_active',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='is_smi_active',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='is_stochastic_active',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='is_supply_demand_active',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='poi_margin_pips',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='scan_timeframes',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='sd_imbalance_threshold',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='sd_timeframe_htf',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='sd_timeframe_ltf',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='smi_sl_pips',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='smi_tp_pips',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='stoch_d_period',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='stoch_k_period',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='stoch_overbought',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='stoch_oversold',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='stoch_slowing',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='timeframe_htf',
        ),
        migrations.RemoveField(
            model_name='marketwatchsettings',
            name='timeframe_ltf',
        ),
        migrations.RemoveField(
            model_name='marketwatchsignal',
            name='dismissed_at',
        ),
        migrations.RemoveField(
            model_name='marketwatchsignal',
            name='entry_price',
        ),
        migrations.RemoveField(
            model_name='marketwatchsignal',
            name='is_dismissed',
        ),
        migrations.RemoveField(
            model_name='marketwatchsignal',
            name='setup_type',
        ),
        migrations.RemoveField(
            model_name='marketwatchsignal',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='marketwatchsignal',
            name='strategy_name',
        ),
        migrations.RemoveField(
            model_name='marketwatchsignal',
            name='take_profit',
        ),
        migrations.RemoveField(
            model_name='marketwatchsignal',
            name='timeframe',
        ),
        migrations.AlterField(
            model_name='marketwatchsettings',
            name='is_scanner_active',
            field=models.BooleanField(default=True, help_text='Activa/Desactiva el escaneo general'),
        ),
        migrations.AlterField(
            model_name='marketwatchsignal',
            name='status',
            field=models.CharField(choices=[('SCANNING', 'Scanning')], default='SCANNING', max_length=20),
        ),
    ]
