# Generated by Django 6.0.2 on 2026-02-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0014_delete_marketwatchhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsettings',
            name='fractal_timeframes',
            field=models.CharField(default='M5,M15,M30,H1,H4,D1', help_text='Temporalidades a evaluar para fractales, separadas por coma', max_length=50),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='is_fractal_active',
            field=models.BooleanField(default=True, help_text='Activa/Desactiva el escaneo de Fractales de Bill Williams'),
        ),
        migrations.AddField(
            model_name='marketwatchsignal',
            name='fractal_price',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Precio del vértice del fractal', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='marketwatchsignal',
            name='fractal_type',
            field=models.CharField(blank=True, help_text='SWING_HIGH o SWING_LOW', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='marketwatchsignal',
            name='matched_tfs',
            field=models.JSONField(default=list, help_text='Lista de temporalidades donde se detectó el fractal'),
        ),
        migrations.AlterField(
            model_name='marketwatchsignal',
            name='status',
            field=models.CharField(choices=[('SCANNING', 'Scanning'), ('FRACTAL_MATCH', 'Fractal Match')], default='SCANNING', max_length=20),
        ),
    ]
