# Generated by Django 6.0.2 on 2026-02-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0015_marketwatchsettings_fractal_timeframes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsignal',
            name='fractal_time',
            field=models.CharField(blank=True, help_text='Hora de la vela del fractal', max_length=50, null=True),
        ),
    ]
