# Generated by Django 6.0.2 on 2026-02-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0016_marketwatchsignal_fractal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsettings',
            name='ema_timeframes',
            field=models.CharField(default='M15,M30,H1,H4', help_text='Temporalidades a evaluar para EMAs, separadas por coma', max_length=50),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='is_ema_active',
            field=models.BooleanField(default=True, help_text='Activa/Desactiva el escaneo de Confluencia EMA'),
        ),
        migrations.AddField(
            model_name='marketwatchsignal',
            name='ema_matched_tfs',
            field=models.JSONField(default=list, help_text='Lista de temporalidades con confluencia EMA'),
        ),
        migrations.AddField(
            model_name='marketwatchsignal',
            name='ema_signal',
            field=models.CharField(blank=True, help_text='BULLISH o BEARISH', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='marketwatchsignal',
            name='status',
            field=models.CharField(choices=[('SCANNING', 'Scanning'), ('FRACTAL_MATCH', 'Fractal Match'), ('EMA_MATCH', 'EMA Match')], default='SCANNING', max_length=20),
        ),
    ]
