# Generated by Django 6.0.2 on 2026-02-28 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0017_marketwatchsettings_ema_timeframes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre amigable (ej: 'Cuenta Principal', 'Prop Firm')", max_length=100)),
                ('terminal_path', models.CharField(help_text='Ruta completa al terminal64.exe del broker', max_length=500)),
                ('is_default', models.BooleanField(default=False, help_text='Terminal por defecto al iniciar el sistema')),
                ('is_active', models.BooleanField(default=False, help_text='Terminal actualmente conectada')),
                ('order', models.IntegerField(default=0, help_text='Orden de display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'MT5 Terminals',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SymbolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_a', models.CharField(help_text='Nombre del símbolo en terminal A', max_length=50)),
                ('symbol_b', models.CharField(help_text='Nombre del símbolo equivalente en terminal B', max_length=50)),
                ('terminal_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_a', to='quant_manager.mt5terminal')),
                ('terminal_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_b', to='quant_manager.mt5terminal')),
            ],
            options={
                'verbose_name_plural': 'Symbol Mappings',
                'unique_together': {('terminal_a', 'terminal_b', 'symbol_a')},
            },
        ),
    ]
