# Generated by Django 6.0.2 on 2026-03-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0018_mt5terminal_symbolmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='risksettings',
            name='global_stop_loss_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Límite de pérdida en % para cierre masivo (ej: 30%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='risksettings',
            name='is_stop_loss_monitor_active',
            field=models.BooleanField(default=False, help_text='Estado del monitor de stop loss general'),
        ),
    ]
