# Generated by Django 6.0.2 on 2026-03-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0019_risksettings_global_stop_loss_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risksettings',
            name='alpha_vantage_api_key',
            field=models.CharField(blank=True, help_text='API Key para obtener datos macro de Alpha Vantage', max_length=100, null=True),
        ),
    ]
