# Generated by Django 6.0.2 on 2026-03-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0020_risksettings_alpha_vantage_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsignal',
            name='tick_volume',
            field=models.BigIntegerField(default=0, help_text='Volumen de ticks actual'),
        ),
        migrations.AddField(
            model_name='marketwatchsignal',
            name='volume_ma',
            field=models.FloatField(default=0.0, help_text='Media móvil del volumen (filtro)'),
        ),
    ]
