# Generated by Django 6.0.2 on 2026-03-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0021_marketwatchsignal_tick_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsettings',
            name='is_volume_filter_active',
            field=models.BooleanField(default=False, help_text='Resaltar símbolos con volumen inusual'),
        ),
        migrations.AddField(
            model_name='marketwatchsettings',
            name='volume_min_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Multiplicador sobre la media para considerar volumen alto (ej: 1.5)', max_digits=4),
        ),
    ]
