# Generated by Django 6.0.2 on 2026-03-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0022_marketwatchsettings_is_volume_filter_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsignal',
            name='ema_200_h1_status',
            field=models.CharField(blank=True, help_text='ABOVE_EMA200 o BELOW_EMA200 en H1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='marketwatchsignal',
            name='ema_matched_tfs',
            field=models.JSONField(default=list, help_text='Lista de TFs donde hay confluencia'),
        ),
    ]
