# Generated by Django 6.0.2 on 2026-03-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0023_marketwatchsignal_ema_200_h1_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsignal',
            name='stoch_data',
            field=models.JSONField(default=dict, help_text='Datos detallados de estocástico por TF'),
        ),
        migrations.AddField(
            model_name='marketwatchsignal',
            name='stoch_status',
            field=models.CharField(blank=True, help_text='BULLISH_CROSS, BEARISH_CROSS, OVERBOUGHT, OVERSOLD', max_length=50, null=True),
        ),
    ]
