# Generated by Django 6.0.2 on 2026-03-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0024_marketwatchsignal_stoch_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsignal',
            name='breakout_m15',
            field=models.CharField(default='RANGE', help_text='RANGE, BULLISH_BREAKOUT, BEARISH_BREAKOUT', max_length=50),
        ),
    ]
