# Generated by Django 6.0.2 on 2026-03-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0026_marketwatchsettings_stoch_breakout_timeframes'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketwatchsignal',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Precio bid actual del tick', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='marketwatchsignal',
            name='symbol_digits',
            field=models.IntegerField(default=5, help_text='Decimales del símbolo según MT5 (forex=5, índices=2, etc.)'),
        ),
        migrations.AlterField(
            model_name='marketwatchsignal',
            name='stoch_status',
            field=models.CharField(blank=True, help_text='BULLISH_CROSS, BEARISH_CROSS, OVERBOUGHT, OVERSOLD', max_length=500, null=True),
        ),
    ]
