# Generated by Django 6.0.2 on 2026-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_manager', '0027_add_current_bid_symbol_digits_fix_stoch_maxlen'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolprofittarget',
            name='is_trailing_active',
            field=models.BooleanField(default=False, help_text='Activa el trailing stop por símbolo'),
        ),
        migrations.AddField(
            model_name='symbolprofittarget',
            name='trail_distance_usd',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Distancia de retroceso en USD para activar el cierre (ej: 5.00)', max_digits=10),
        ),
        migrations.AddField(
            model_name='symbolprofittarget',
            name='trail_peak_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Máximo profit registrado desde que el trailing está activo (auto-actualizado)', max_digits=10),
        ),
    ]
